#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : inflection
Version  : 0.4.0
Release  : 8
URL      : https://files.pythonhosted.org/packages/e8/dc/3986343faf9631d8bc61d8a6a1331b5f4f08723dbce3b39f524c367a1621/inflection-0.4.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/e8/dc/3986343faf9631d8bc61d8a6a1331b5f4f08723dbce3b39f524c367a1621/inflection-0.4.0.tar.gz
Summary  : A port of Ruby on Rails inflector to Python
Group    : Development/Tools
License  : MIT
Requires: inflection-python = %{version}-%{release}
Requires: inflection-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
Inflection
==========
|build status|_
.. |build status| image:: https://travis-ci.org/jpvanhal/inflection.svg?branch=master
:alt: Build Status
.. _build status: http://travis-ci.org/jpvanhal/inflection

%package python
Summary: python components for the inflection package.
Group: Default
Requires: inflection-python3 = %{version}-%{release}

%description python
python components for the inflection package.


%package python3
Summary: python3 components for the inflection package.
Group: Default
Requires: python3-core
Provides: pypi(inflection)

%description python3
python3 components for the inflection package.


%prep
%setup -q -n inflection-0.4.0
cd %{_builddir}/inflection-0.4.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1586271468
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
